runtime: python38

#service: tpt-flask

handlers:
  - url: /s/static
    static_dir: static

  - url: /s/.*
    secure: always
    script: auto

  - url: /(.*\.css)
    mime_type: text/css
    static_files: politics-test/dist/\1
    upload: politics-test/dist/(.*\.css)

  - url: /(.*\.ico)
    mime_type: image/x-icon
    static_files: politics-test/dist/\1
    upload: politics-test/dist/(.*\.ico)
    expiration: "7d"

  - url: /(.*\.js)
    mime_type: text/javascript
    static_files: politics-test/dist/\1
    upload: politics-test/dist/(.*\.js)

  - url: /(.*\.(svg|svgz))
    mime_type: images/svg+xml
    static_files: politics-test/dist/\1
    upload: politics-test/dist/(.*\.(svg|svgz))

  - url: /(.*\..+)$
    secure: always
    static_files: politics-test/dist/\1
    upload: politics-test/dist/(.*\..+)$

  - url: /.*
    secure: always
    static_files: politics-test/dist/index.html
    upload: politics-test/dist/index.html
