runtime: python38

#service: tpt-flask

handlers:
  - url: /s/static
    static_dir: static

  - url: /s/.*
    secure: always
    script: auto

  - url: /
    secure: always
    static_dir: politics_test
