steps:
  # Install Flask App
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Clone front-end (React) app repo
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/hallcode/politics-test.git"]

  # yarn install
  - name: node
    entrypoint: yarn
    args:
      - install
      - "?production"
    dir: "politics-test"

  # yarn build
  - name: node
    entrypoint: yarn
    args:
      - build
    dir: "politics-test"

  # Deploy to app-engine
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: app
    args: ["deploy"]
