steps:
  # Clone front-end (React) app repo
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/hallcode/politics-test.git"]

  # yarn install
  - name: node
    entrypoint: yarn
    args:
      - install
    dir: "politics-test"

  # yarn build
  - name: node
    entrypoint: yarn
    args:
      - build
    dir: "politics-test"

  # Deploy to app-engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - gcloud
      - app
      - deploy
